# Generated by Django 3.2 on 2023-03-15 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20230315_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='titles.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(to='titles.Genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)], verbose_name='Дата выпуска'),
        ),
    ]
