# Generated by Django 3.2 on 2023-03-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20230315_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сomments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='сomments',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Сomments',
        ),
    ]
