# Generated by Django 3.2 on 2023-03-16 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '0006_auto_20230316_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('score', models.SmallIntegerField(choices=[(1, '1. Неудовлетворительно'), (2, '2. Почти неудовлетворительно'), (3, '3. Удовлетворительно'), (4, '4. Весьма удовлетворительно'), (5, '5. Почти хорошо'), (6, '6. Хорошо'), (7, '7. Очень хорошо'), (8, '8. Почти отлично'), (9, '9. Отлично'), (10, '10. Превосходно')], verbose_name='Оценка произведения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.titles', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['pub_date'],
                'default_related_name': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Сomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.reviews', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментрий к отзывы',
                'verbose_name_plural': 'Комментарии к отзыву',
                'ordering': ['pub_date'],
                'default_related_name': 'comments',
            },
        ),
    ]
