# Generated by Django 3.2 on 2023-03-18 19:11

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_reviews_unique_review_from_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.SmallIntegerField(choices=[(1, '1. Неудовлетворительно'), (2, '2. Почти неудовлетворительно'), (3, '3. Удовлетворительно'), (4, '4. Весьма удовлетворительно'), (5, '5. Почти хорошо'), (6, '6. Хорошо'), (7, '7. Очень хорошо'), (8, '8. Почти отлично'), (9, '9. Отлично'), (10, '10. Превосходно')], validators=[reviews.validators.score_validator], verbose_name='Оценка произведения'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
